version: "3.9"

services:
  siberiana_graphql:
    container_name: siberiana_graphql
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - 4000:4000
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_SSL_MODE: ${POSTGRES_SSL_MODE}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_PORT: ${MINIO_PORT}
      MINIO_ACCESS_KEY_ID: ${MINIO_ACCESS_KEY_ID}
      MINIO_SECRET_ACCESS_KEY: ${MINIO_SECRET_ACCESS_KEY}
      MINIO_USE_SSL: ${MINIO_USE_SSL}
      MINIO_DEFAULT_BUCKET: ${MINIO_DEFAULT_BUCKET}
      OIDC_USERINFO_ENDPOINT: ${OIDC_USERINFO_ENDPOINT}
    depends_on:
      - siberiana_postgres
      - siberiana_redis
    networks:
      - siberiana-network

  siberiana_postgres:
    container_name: siberiana_postgres
    build:
      context: .
      dockerfile: ./docker/Dockerfile.postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - siberiana_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - siberiana-network

  siberiana_redis:
    container_name: siberiana_redis
    build:
      context: .
      dockerfile: ./docker/Dockerfile.redis
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - siberiana-network

volumes:
  siberiana_cache:
    external: true
  siberiana_data:
    external: true

networks:
  siberiana-network:
    external: true
