version: "3"

tasks:
  clean:
    - go run ./internal/entclean/main.go
  env:
    - cp .env.example .env
  network:
    - docker network inspect siberiana-network >/dev/null 2>&1 || docker network create siberiana-network
  volume:
    cmds:
      - docker volume inspect siberiana_data >/dev/null 2>&1 || docker volume create siberiana_data
      - docker volume inspect siberiana_cache >/dev/null 2>&1 || docker volume create siberiana_cache
  db:
    cmds:
      - docker-compose up -d siberiana_postgres siberiana_redis
    deps: [network, volume]
  build-image:
    cmds:
      - docker-compose up --build --force-recreate -d
    deps: [db]
  up:
    cmds:
      - docker-compose up -d siberiana_graphql
    deps: [db]
  stop:
    cmds:
      - docker-compose kill || true
      - docker-compose rm --force || true
  clear:
    - docker-compose down -v --remove-orphans || true
  dev:
    - air
  gen:
    - go generate .
  build-binary:
    - go build -o bin/http cmd/http/main.go
  start:
    - bin/http
  install:
    cmds:
      - go install github.com/go-task/task/v3/cmd/task@latest
      - go install entgo.io/ent/cmd/ent@latest
      - go mod tidy
