// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/dkrasnovdev/heritage-api/ent/country"
	"github.com/dkrasnovdev/heritage-api/ent/location"
	"github.com/dkrasnovdev/heritage-api/ent/predicate"
)

// CountryUpdate is the builder for updating Country entities.
type CountryUpdate struct {
	config
	hooks    []Hook
	mutation *CountryMutation
}

// Where appends a list predicates to the CountryUpdate builder.
func (cu *CountryUpdate) Where(ps ...predicate.Country) *CountryUpdate {
	cu.mutation.Where(ps...)
	return cu
}

// SetCreatedBy sets the "created_by" field.
func (cu *CountryUpdate) SetCreatedBy(s string) *CountryUpdate {
	cu.mutation.SetCreatedBy(s)
	return cu
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (cu *CountryUpdate) SetNillableCreatedBy(s *string) *CountryUpdate {
	if s != nil {
		cu.SetCreatedBy(*s)
	}
	return cu
}

// ClearCreatedBy clears the value of the "created_by" field.
func (cu *CountryUpdate) ClearCreatedBy() *CountryUpdate {
	cu.mutation.ClearCreatedBy()
	return cu
}

// SetUpdatedAt sets the "updated_at" field.
func (cu *CountryUpdate) SetUpdatedAt(t time.Time) *CountryUpdate {
	cu.mutation.SetUpdatedAt(t)
	return cu
}

// SetUpdatedBy sets the "updated_by" field.
func (cu *CountryUpdate) SetUpdatedBy(s string) *CountryUpdate {
	cu.mutation.SetUpdatedBy(s)
	return cu
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (cu *CountryUpdate) SetNillableUpdatedBy(s *string) *CountryUpdate {
	if s != nil {
		cu.SetUpdatedBy(*s)
	}
	return cu
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (cu *CountryUpdate) ClearUpdatedBy() *CountryUpdate {
	cu.mutation.ClearUpdatedBy()
	return cu
}

// SetAbbreviation sets the "abbreviation" field.
func (cu *CountryUpdate) SetAbbreviation(s string) *CountryUpdate {
	cu.mutation.SetAbbreviation(s)
	return cu
}

// SetNillableAbbreviation sets the "abbreviation" field if the given value is not nil.
func (cu *CountryUpdate) SetNillableAbbreviation(s *string) *CountryUpdate {
	if s != nil {
		cu.SetAbbreviation(*s)
	}
	return cu
}

// ClearAbbreviation clears the value of the "abbreviation" field.
func (cu *CountryUpdate) ClearAbbreviation() *CountryUpdate {
	cu.mutation.ClearAbbreviation()
	return cu
}

// SetDisplayName sets the "display_name" field.
func (cu *CountryUpdate) SetDisplayName(s string) *CountryUpdate {
	cu.mutation.SetDisplayName(s)
	return cu
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (cu *CountryUpdate) SetNillableDisplayName(s *string) *CountryUpdate {
	if s != nil {
		cu.SetDisplayName(*s)
	}
	return cu
}

// ClearDisplayName clears the value of the "display_name" field.
func (cu *CountryUpdate) ClearDisplayName() *CountryUpdate {
	cu.mutation.ClearDisplayName()
	return cu
}

// SetDescription sets the "description" field.
func (cu *CountryUpdate) SetDescription(s string) *CountryUpdate {
	cu.mutation.SetDescription(s)
	return cu
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (cu *CountryUpdate) SetNillableDescription(s *string) *CountryUpdate {
	if s != nil {
		cu.SetDescription(*s)
	}
	return cu
}

// ClearDescription clears the value of the "description" field.
func (cu *CountryUpdate) ClearDescription() *CountryUpdate {
	cu.mutation.ClearDescription()
	return cu
}

// SetExternalLinks sets the "external_links" field.
func (cu *CountryUpdate) SetExternalLinks(s []string) *CountryUpdate {
	cu.mutation.SetExternalLinks(s)
	return cu
}

// AppendExternalLinks appends s to the "external_links" field.
func (cu *CountryUpdate) AppendExternalLinks(s []string) *CountryUpdate {
	cu.mutation.AppendExternalLinks(s)
	return cu
}

// ClearExternalLinks clears the value of the "external_links" field.
func (cu *CountryUpdate) ClearExternalLinks() *CountryUpdate {
	cu.mutation.ClearExternalLinks()
	return cu
}

// SetLocationID sets the "location" edge to the Location entity by ID.
func (cu *CountryUpdate) SetLocationID(id int) *CountryUpdate {
	cu.mutation.SetLocationID(id)
	return cu
}

// SetNillableLocationID sets the "location" edge to the Location entity by ID if the given value is not nil.
func (cu *CountryUpdate) SetNillableLocationID(id *int) *CountryUpdate {
	if id != nil {
		cu = cu.SetLocationID(*id)
	}
	return cu
}

// SetLocation sets the "location" edge to the Location entity.
func (cu *CountryUpdate) SetLocation(l *Location) *CountryUpdate {
	return cu.SetLocationID(l.ID)
}

// Mutation returns the CountryMutation object of the builder.
func (cu *CountryUpdate) Mutation() *CountryMutation {
	return cu.mutation
}

// ClearLocation clears the "location" edge to the Location entity.
func (cu *CountryUpdate) ClearLocation() *CountryUpdate {
	cu.mutation.ClearLocation()
	return cu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (cu *CountryUpdate) Save(ctx context.Context) (int, error) {
	if err := cu.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, cu.sqlSave, cu.mutation, cu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cu *CountryUpdate) SaveX(ctx context.Context) int {
	affected, err := cu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cu *CountryUpdate) Exec(ctx context.Context) error {
	_, err := cu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cu *CountryUpdate) ExecX(ctx context.Context) {
	if err := cu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cu *CountryUpdate) defaults() error {
	if _, ok := cu.mutation.UpdatedAt(); !ok {
		if country.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized country.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := country.UpdateDefaultUpdatedAt()
		cu.mutation.SetUpdatedAt(v)
	}
	return nil
}

func (cu *CountryUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(country.Table, country.Columns, sqlgraph.NewFieldSpec(country.FieldID, field.TypeInt))
	if ps := cu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cu.mutation.CreatedBy(); ok {
		_spec.SetField(country.FieldCreatedBy, field.TypeString, value)
	}
	if cu.mutation.CreatedByCleared() {
		_spec.ClearField(country.FieldCreatedBy, field.TypeString)
	}
	if value, ok := cu.mutation.UpdatedAt(); ok {
		_spec.SetField(country.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := cu.mutation.UpdatedBy(); ok {
		_spec.SetField(country.FieldUpdatedBy, field.TypeString, value)
	}
	if cu.mutation.UpdatedByCleared() {
		_spec.ClearField(country.FieldUpdatedBy, field.TypeString)
	}
	if value, ok := cu.mutation.Abbreviation(); ok {
		_spec.SetField(country.FieldAbbreviation, field.TypeString, value)
	}
	if cu.mutation.AbbreviationCleared() {
		_spec.ClearField(country.FieldAbbreviation, field.TypeString)
	}
	if value, ok := cu.mutation.DisplayName(); ok {
		_spec.SetField(country.FieldDisplayName, field.TypeString, value)
	}
	if cu.mutation.DisplayNameCleared() {
		_spec.ClearField(country.FieldDisplayName, field.TypeString)
	}
	if value, ok := cu.mutation.Description(); ok {
		_spec.SetField(country.FieldDescription, field.TypeString, value)
	}
	if cu.mutation.DescriptionCleared() {
		_spec.ClearField(country.FieldDescription, field.TypeString)
	}
	if value, ok := cu.mutation.ExternalLinks(); ok {
		_spec.SetField(country.FieldExternalLinks, field.TypeJSON, value)
	}
	if value, ok := cu.mutation.AppendedExternalLinks(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, country.FieldExternalLinks, value)
		})
	}
	if cu.mutation.ExternalLinksCleared() {
		_spec.ClearField(country.FieldExternalLinks, field.TypeJSON)
	}
	if cu.mutation.LocationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   country.LocationTable,
			Columns: []string{country.LocationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(location.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.LocationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   country.LocationTable,
			Columns: []string{country.LocationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(location.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, cu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{country.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	cu.mutation.done = true
	return n, nil
}

// CountryUpdateOne is the builder for updating a single Country entity.
type CountryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CountryMutation
}

// SetCreatedBy sets the "created_by" field.
func (cuo *CountryUpdateOne) SetCreatedBy(s string) *CountryUpdateOne {
	cuo.mutation.SetCreatedBy(s)
	return cuo
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (cuo *CountryUpdateOne) SetNillableCreatedBy(s *string) *CountryUpdateOne {
	if s != nil {
		cuo.SetCreatedBy(*s)
	}
	return cuo
}

// ClearCreatedBy clears the value of the "created_by" field.
func (cuo *CountryUpdateOne) ClearCreatedBy() *CountryUpdateOne {
	cuo.mutation.ClearCreatedBy()
	return cuo
}

// SetUpdatedAt sets the "updated_at" field.
func (cuo *CountryUpdateOne) SetUpdatedAt(t time.Time) *CountryUpdateOne {
	cuo.mutation.SetUpdatedAt(t)
	return cuo
}

// SetUpdatedBy sets the "updated_by" field.
func (cuo *CountryUpdateOne) SetUpdatedBy(s string) *CountryUpdateOne {
	cuo.mutation.SetUpdatedBy(s)
	return cuo
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (cuo *CountryUpdateOne) SetNillableUpdatedBy(s *string) *CountryUpdateOne {
	if s != nil {
		cuo.SetUpdatedBy(*s)
	}
	return cuo
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (cuo *CountryUpdateOne) ClearUpdatedBy() *CountryUpdateOne {
	cuo.mutation.ClearUpdatedBy()
	return cuo
}

// SetAbbreviation sets the "abbreviation" field.
func (cuo *CountryUpdateOne) SetAbbreviation(s string) *CountryUpdateOne {
	cuo.mutation.SetAbbreviation(s)
	return cuo
}

// SetNillableAbbreviation sets the "abbreviation" field if the given value is not nil.
func (cuo *CountryUpdateOne) SetNillableAbbreviation(s *string) *CountryUpdateOne {
	if s != nil {
		cuo.SetAbbreviation(*s)
	}
	return cuo
}

// ClearAbbreviation clears the value of the "abbreviation" field.
func (cuo *CountryUpdateOne) ClearAbbreviation() *CountryUpdateOne {
	cuo.mutation.ClearAbbreviation()
	return cuo
}

// SetDisplayName sets the "display_name" field.
func (cuo *CountryUpdateOne) SetDisplayName(s string) *CountryUpdateOne {
	cuo.mutation.SetDisplayName(s)
	return cuo
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (cuo *CountryUpdateOne) SetNillableDisplayName(s *string) *CountryUpdateOne {
	if s != nil {
		cuo.SetDisplayName(*s)
	}
	return cuo
}

// ClearDisplayName clears the value of the "display_name" field.
func (cuo *CountryUpdateOne) ClearDisplayName() *CountryUpdateOne {
	cuo.mutation.ClearDisplayName()
	return cuo
}

// SetDescription sets the "description" field.
func (cuo *CountryUpdateOne) SetDescription(s string) *CountryUpdateOne {
	cuo.mutation.SetDescription(s)
	return cuo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (cuo *CountryUpdateOne) SetNillableDescription(s *string) *CountryUpdateOne {
	if s != nil {
		cuo.SetDescription(*s)
	}
	return cuo
}

// ClearDescription clears the value of the "description" field.
func (cuo *CountryUpdateOne) ClearDescription() *CountryUpdateOne {
	cuo.mutation.ClearDescription()
	return cuo
}

// SetExternalLinks sets the "external_links" field.
func (cuo *CountryUpdateOne) SetExternalLinks(s []string) *CountryUpdateOne {
	cuo.mutation.SetExternalLinks(s)
	return cuo
}

// AppendExternalLinks appends s to the "external_links" field.
func (cuo *CountryUpdateOne) AppendExternalLinks(s []string) *CountryUpdateOne {
	cuo.mutation.AppendExternalLinks(s)
	return cuo
}

// ClearExternalLinks clears the value of the "external_links" field.
func (cuo *CountryUpdateOne) ClearExternalLinks() *CountryUpdateOne {
	cuo.mutation.ClearExternalLinks()
	return cuo
}

// SetLocationID sets the "location" edge to the Location entity by ID.
func (cuo *CountryUpdateOne) SetLocationID(id int) *CountryUpdateOne {
	cuo.mutation.SetLocationID(id)
	return cuo
}

// SetNillableLocationID sets the "location" edge to the Location entity by ID if the given value is not nil.
func (cuo *CountryUpdateOne) SetNillableLocationID(id *int) *CountryUpdateOne {
	if id != nil {
		cuo = cuo.SetLocationID(*id)
	}
	return cuo
}

// SetLocation sets the "location" edge to the Location entity.
func (cuo *CountryUpdateOne) SetLocation(l *Location) *CountryUpdateOne {
	return cuo.SetLocationID(l.ID)
}

// Mutation returns the CountryMutation object of the builder.
func (cuo *CountryUpdateOne) Mutation() *CountryMutation {
	return cuo.mutation
}

// ClearLocation clears the "location" edge to the Location entity.
func (cuo *CountryUpdateOne) ClearLocation() *CountryUpdateOne {
	cuo.mutation.ClearLocation()
	return cuo
}

// Where appends a list predicates to the CountryUpdate builder.
func (cuo *CountryUpdateOne) Where(ps ...predicate.Country) *CountryUpdateOne {
	cuo.mutation.Where(ps...)
	return cuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (cuo *CountryUpdateOne) Select(field string, fields ...string) *CountryUpdateOne {
	cuo.fields = append([]string{field}, fields...)
	return cuo
}

// Save executes the query and returns the updated Country entity.
func (cuo *CountryUpdateOne) Save(ctx context.Context) (*Country, error) {
	if err := cuo.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, cuo.sqlSave, cuo.mutation, cuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cuo *CountryUpdateOne) SaveX(ctx context.Context) *Country {
	node, err := cuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (cuo *CountryUpdateOne) Exec(ctx context.Context) error {
	_, err := cuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cuo *CountryUpdateOne) ExecX(ctx context.Context) {
	if err := cuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cuo *CountryUpdateOne) defaults() error {
	if _, ok := cuo.mutation.UpdatedAt(); !ok {
		if country.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized country.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := country.UpdateDefaultUpdatedAt()
		cuo.mutation.SetUpdatedAt(v)
	}
	return nil
}

func (cuo *CountryUpdateOne) sqlSave(ctx context.Context) (_node *Country, err error) {
	_spec := sqlgraph.NewUpdateSpec(country.Table, country.Columns, sqlgraph.NewFieldSpec(country.FieldID, field.TypeInt))
	id, ok := cuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Country.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := cuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, country.FieldID)
		for _, f := range fields {
			if !country.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != country.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := cuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cuo.mutation.CreatedBy(); ok {
		_spec.SetField(country.FieldCreatedBy, field.TypeString, value)
	}
	if cuo.mutation.CreatedByCleared() {
		_spec.ClearField(country.FieldCreatedBy, field.TypeString)
	}
	if value, ok := cuo.mutation.UpdatedAt(); ok {
		_spec.SetField(country.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := cuo.mutation.UpdatedBy(); ok {
		_spec.SetField(country.FieldUpdatedBy, field.TypeString, value)
	}
	if cuo.mutation.UpdatedByCleared() {
		_spec.ClearField(country.FieldUpdatedBy, field.TypeString)
	}
	if value, ok := cuo.mutation.Abbreviation(); ok {
		_spec.SetField(country.FieldAbbreviation, field.TypeString, value)
	}
	if cuo.mutation.AbbreviationCleared() {
		_spec.ClearField(country.FieldAbbreviation, field.TypeString)
	}
	if value, ok := cuo.mutation.DisplayName(); ok {
		_spec.SetField(country.FieldDisplayName, field.TypeString, value)
	}
	if cuo.mutation.DisplayNameCleared() {
		_spec.ClearField(country.FieldDisplayName, field.TypeString)
	}
	if value, ok := cuo.mutation.Description(); ok {
		_spec.SetField(country.FieldDescription, field.TypeString, value)
	}
	if cuo.mutation.DescriptionCleared() {
		_spec.ClearField(country.FieldDescription, field.TypeString)
	}
	if value, ok := cuo.mutation.ExternalLinks(); ok {
		_spec.SetField(country.FieldExternalLinks, field.TypeJSON, value)
	}
	if value, ok := cuo.mutation.AppendedExternalLinks(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, country.FieldExternalLinks, value)
		})
	}
	if cuo.mutation.ExternalLinksCleared() {
		_spec.ClearField(country.FieldExternalLinks, field.TypeJSON)
	}
	if cuo.mutation.LocationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   country.LocationTable,
			Columns: []string{country.LocationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(location.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.LocationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   country.LocationTable,
			Columns: []string{country.LocationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(location.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Country{config: cuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, cuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{country.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	cuo.mutation.done = true
	return _node, nil
}
